# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
strategy:
  matrix:
    node_8_x:
      node_version: 8.12.0
    node_9_x:
      node_version: 9.6.0

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: npm install
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.2'
  displayName: 'Install Node.js'

- script: |
    sudo npm install
    sudo npm run build
  displayName: 'npm install and build'

- script: sudo npm install --only=dev
- script: sudo npm install -g @angular/cli
- script: sudo npm install
- script: sudo yarn install
- script: sudo npm install compile-run --save
- script: tsc --target ES6 --strict true --project tsconfigs/production.json